---
title: "Data Manipulation Class"
date: "2023-09-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Class

```{r}
library(tidyverse)
```

```{r}
litters_df =
  read_csv("FAS_litters.csv")

litters_df =
  janitor::clean_names(litters_df)
```

```{r}
pups_df =
  read_csv("FAS_pups.csv")

pups_df =
  janitor::clean_names(pups_df)
```

## Select

'select' is used to select columns!

```{r}
select(litters_df, group, litter_number, gd0_weight:gd_of_birth)
```

: means through

Can rename variables in 'select'

```{r}
select(litters_df, group, id = litter_number)
```

Use everything() if you want to sort some columns in a certain order and keep everything else

```{r}
select(litters_df, group, everything())
```

```{r}
rename(litters_df, id = litter_number)
```

## Filter

Keep every row that has this specific value, Con7
  2 equal signs means TRUE
```{r}
filter(litters_df, group == "Con7")
```

| means OR

## Mutate

```{r}
mutate(litters_df, wt_gain = gd18_weight - gd0_weight)
```

## Arrange

```{r}
arrange(litters_df, group, gd0_weight)
```

## Pipes |>

```{r}
litters_df =
  read_csv("FAS_litters.csv") |> 
  janitor::clean_names() |> 
  select(-starts_with("pups")) |> 
  mutate(
    group = str_to_lower(group),
    weight_gain = gd18_weight - gd0_weight,
  ) |> 
  drop_na(weight_gain) |> 
  arrange(group, weight_gain)
```
```
